### ISSUE TITLE
Updating to the latest version

### ISSUE THREAD

**Issue by nonnymoose** [hypersad/atom-armv7l#14]
@hypersad What did you mean when you said that mksnapshot binaries for ARM were broken?

Anyway, now the latest release at atom/atom is 1.17.2, and I'd really like to see a build of _that_ for ARM. Is there anything I can do to help?

**Comment by nonnymoose** [comment]
Oh, I found it...

**Comment by hypersad** [comment]
By downloading armv7l electron-mksnapshot binaries we got i386 binaries.

**Comment by wsngamerz** [comment]
@hypersad there is a mksnapshot binary for armv7l on the first v1.7.0 beta pre-release [Here](https://github.com/electron/electron/releases/tag/v1.7.0)

**Comment by hypersad** [comment]
@wsngamerz, nope.
`hypersad@xubuntu:~$ ./mksnapshot
bash: ./mksnapshot: cannot execute binary file: Exec format error
hypersad@xubuntu:~$ file mksnapshot
mksnapshot: ELF 32-bit LSB  shared object, **Intel 80386**, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, BuildID[sha1]=ed09ef1a8894d4f20451a64e6c35102e5833baf8, not stripped`

**Comment by wsngamerz** [comment]
ah okay

**Comment by hypersad** [comment]
@wsngamerz, one of the building parts in new versions of Atom - is making snapshot. I can try to skip this part, but I don't know what can happens if I do that.

**Comment by nonnymoose** [comment]
@hypersad I checked and *none* of the mksnapshot binaries have *ever* been compiled correctly for arm. It might be a good idea to file an issue with electron/electron.

In the meantime​, you could try installing the `qemu-user-static` package and then running the i386 version of mksnapshot. (Qemu is a CPU emulator, and -user-static will automatically run other binaries in the emulator) Expect it to be very slow, though.

**Comment by nonnymoose** [comment]
@hypersad How did you know that you needed mksnapshot? Did you see it in any build instructions?

**Comment by hypersad** [comment]
@noonymoose before creating this repo I tried to build 1.17.0

**Comment by nonnymoose** [comment]
@hypersad And it just gave you that error? No other explanation?

**Comment by hypersad** [comment]
electron/electron#11413
electron/mksnapshot#3

Look there for details.

**Comment by hypersad** [comment]
Closed due to repository update.
