### ISSUE TITLE
Build Fail at 'Dumping Symbols' with 'Unable to find the "dump_syms'

### ISSUE THREAD

**Issue by ajarmst** [hypersad/atom-armv7l#16]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Build Fail at 'Dumping Symbols' with 'Unable to find the "dump_syms'

### Steps to Reproduce

1. Try to Build

**Expected behavior:** [What you expect to happen]
Success

**Actual behavior:** [What actually happens]
Failure per title description.  See below for detail on output.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Versions
* Raspberry Pi 3
* uname -a: Linux ajarpi 4.9.28-v7+ #998 SMP Mon May 15 16:55:39 BST 2017 armv7l GNU/Linux
* Node:	v6.10.2
* Npm:	v3.10.5
* cat /etc/issue: Raspbian GNU/Linux 8 \n \l
### Additional Information

Console output during build:

```
root@ajarpi:~/Github/atom-armv7l# node script/build
Node:	v6.10.2
Npm:	v3.10.5
Installing script dependencies
Installing apm
Installing modules ✓
Wrote Dependencies Fingerprint: /root/Github/atom-armv7l/node_modules/.dependencies-fingerprint 1378bc15a3a7190fe2ea8d12d9ba9dc81033cd7e
Cleaning /root/Github/atom-armv7l/out
Copying assets to /root/Github/atom-armv7l/out/app
Transpiling Babel paths in /root/Github/atom-armv7l/out/app
Transpiling CoffeeScript paths in /root/Github/atom-armv7l/out/app
Transpiling CSON paths in /root/Github/atom-armv7l/out/app
Transpiling PEG.js paths in /root/Github/atom-armv7l/out/app
Generating module cache for /root/Github/atom-armv7l/out/app
Generating pre-built less cache in /root/Github/atom-armv7l/out/app/less-compile-cache
Generating metadata for /root/Github/atom-armv7l/out/app/package.json
Generating API docs at /root/Github/atom-armv7l/docs/output/atom-api.json
Dumping symbols in /root/Github/atom-armv7l/out/symbols
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Error: Unable to find the "dump_syms"
    at /root/Github/atom-armv7l/script/lib/dump-symbols.js:26:15
    at Object.module.exports.dumpSymbol (/root/Github/atom-armv7l/script/node_modules/minidump/lib/minidump.js:65:5)
    at /root/Github/atom-armv7l/script/lib/dump-symbols.js:23:14
    at dumpSymbol (/root/Github/atom-armv7l/script/lib/dump-symbols.js:22:10)
    at Array.map (native)
    at module.exports (/root/Github/atom-armv7l/script/lib/dump-symbols.js:15:36)
    at Object.<anonymous> (/root/Github/atom-armv7l/script/build:62:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

```

**Comment by hypersad** [comment]
Try to delete full atom-armv7l repository, download it again and start building. Do not ley your device sleep during building.

**Comment by wsngamerz** [comment]
I Just built atom on my rpi3 and it worked fine, I've created a Debian package too. Download it [Here](https://www.dropbox.com/s/9pnyiosek8d3sbb/atom-armhf.deb?dl=0) and install it using `sudo dpkg -i atom-armhf.deb`. After that, download and run it, then close it, then run the `atom.firstboot.sh` script.
