### ISSUE TITLE
Atom package issues

### ISSUE THREAD

**Issue by wsngamerz** [hypersad/atom-armv7l#17]
When I startup atom, two packages seem to have issues with some functions. I'm wondering weather it's the version of atom 1.15.0. Do I need to install a specific version of the packages or is it something else. 
![dsc_0035](https://user-images.githubusercontent.com/15077095/28239275-5daec486-6960-11e7-8993-eb14b3781284.JPG)

**Comment by hypersad** [comment]
Did you upgraded packages after installing?

**Comment by wsngamerz** [comment]
I haven't upgraded any packages, just uses the default ones installed by atom.firstboot.sh

**Comment by hypersad** [comment]
What version of broken packages do you have? You can check it in settings.

**Comment by wsngamerz** [comment]
I'll go and check.

**Comment by wsngamerz** [comment]
image-view-package is at 0.62.1
status-bar-package is at 1.8.11
tabs-package is at 0.106.2

**Comment by wsngamerz** [comment]
i reckon that it is because in the ```atom.firstboot.sh``` file, it doesn't specify a version for every package

**Comment by wsngamerz** [comment]
i have found that the following packages need to have a specific version so they don't break:

tabs package at v0.106.1
status-bar at v1.8.10
image-view at v0.62.0

this only fixes my issues but if i upgrade to any higher version, some packages start to break
