### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by combs** [hypersad/atom-armv7l#18]
Would you consider including a .deb for download? Couldn't get the build chain running, but I'm able to use the armv7l binary on my aarch64/ARM64 machine (Pinebook) with a little hoop-jumping. Having ready access to a .deb would have made this easier.

Thanks!

**Comment by djarami** [comment]
It would also be great to have one for raspberrypi3.  I would be willing to help with that. 

Regards
David Jaramillo 
djarami@gmail.com
561-703-6860

**Comment by wsngamerz** [comment]
I've created a Debian package for atom (Built from my rpi3). Download it [Here](https://www.dropbox.com/s/9pnyiosek8d3sbb/atom-armhf.deb?dl=1) and install it using ```sudo dpkg -i atom-armhf.deb```. After that, open it, then close it, then run the ```atom.firstboot.sh``` script from this repo.
