### ISSUE TITLE
Why can I not use node 7+

### ISSUE THREAD

**Issue by yamboy1** [hypersad/atom-armv7l#20]
This doesn't actually affect me because I use NVM but I am intruiged to know why I have to use node 6 to install atom-armv7l

**Comment by hypersad** [comment]
As I remember, it was in the official Atom linux building guide, so I included it here. Maybe, you can build new versions of Atom with Node.JS =>7.0.0, but I don't sure that you can build this version with it.

**Comment by yamboy1** [comment]
@hypersad This says it should work https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#requirements

**Comment by yamboy1** [comment]
Although this says otherwise https://github.com/atom/apm/issues/636
