### ISSUE TITLE
atom-armv7l/apm/node_modules/atom-package-manager/bin/node: No such file or directory

### ISSUE THREAD

**Issue by jason-neal** [hypersad/atom-armv7l#22]
Trying to build on rpi2 following the readme instructions to the letter:

```
pi@raspberrypi:~/work/companion_simulations $ uname -m
armv7l

```
I get an error when trying to the build. 
```
pi@raspberrypi:~/Downloads/atom-armv7l $ node script/build

Node:	v6.10.2
Npm:	v3.10.5
Installing script dependencies
Installing apm
/home/pi/Downloads/atom-armv7l/apm/node_modules/atom-package-manager/bin/apm: line 37: /home/pi/Downloads/atom-armv7l/apm/node_modules/atom-package-manager/bin/node: No such file or directory
child_process.js:504
    throw err;
    ^

Error: Command failed: /home/pi/Downloads/atom-armv7l/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:481:13)
    at Object.execFileSync (child_process.js:501:13)
    at module.exports (/home/pi/Downloads/atom-armv7l/script/lib/install-atom-dependencies.js:15:16)
    at Object.<anonymous> (/home/pi/Downloads/atom-armv7l/script/bootstrap:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

```

Any ideas how to resolve this?

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by nlsdfnbch** [comment]
related to #19, I believe. Looks like the same clusterfuck. I wasn't able to resolve it on my end, unfortunately. :/

**Comment by hypersad** [comment]
Closed due to repository update.
