### ISSUE TITLE
Dependency issue (git-utils) on Ubuntu mate 16.04.2 for Raspberry pi

### ISSUE THREAD

**Issue by tormodvh** [hypersad/atom-armv7l#23]
Summary:
When I started Atom I got something looking like a chrome/Firefox developer environment with a console saying: 
Error: can't find module 'git-utils' (index.js:56
at Module._resolveFilename: (Module.js:455:15) 
...
...

Details:
I have done this two times now so I think it is consistent.

I have done:
1: "burn"  the image "ubuntu-mate-16.04.2-desktop-armhf-raspberry-pi.img.xz" to an sd card.
2: booted my Raspberry pi 3.
3: Opened Firefox and searched for "how to install atom arm" 
4: Opened Issue 7822 :-)
5: found the link to your repo
6: followed the steps in README.md ( installing nvm and node.js ++)
7: node script/build --create-debian-package
8: ./atom.firstboot.sh ( this does not give me icons in menues or atom in the path so...)
9: sudo dpkg -i atom-armhf.deb
10: start Atom
11:  ./atom.firstboot.sh  ( again)
12: still no 'git-utils'

by now I have no Firefox since it after this crashes on startup. it did that last time too. the first time it crashed meanwhile running "atom.firstboot.sh"(I think). I am no Linux Ninja and last time I was not able to make Firefox work again of chromium either. This is the reason I tried i the second time. And here I'm now. With no working Atom and no working Firefox. I really want a good code editor even i'm on limited hardware.

Is it possible that some of the scripts mes with some package that Firefox depend on?
And is it only me that does not have "git-utils" i tried to install it by "npm install git-util" but is was not found.

I blame, You fix? :-)

Seriously I love to have Atom on my rpi3 and I'm dying to be able to develop software on my rpi3. 
Can you locate and solve my problem?

Tormod

**Comment by hypersad** [comment]
Closed due to repository update.
