### ISSUE TITLE
Need the .deb of 1.23 armhf 

### ISSUE THREAD

**Issue by dianaxxyyzz** [hypersad/atom-armv7l#3]
Please give us the .deb of 1.23 armhf

**Comment by hypersad** [comment]
Why you're unable to build it youtself?

**Comment by dianaxxyyzz** [comment]
I deleted the build files and I do not remember exactly the erreor but it was a java illegal error .I had a atom binary and when I open it it just show Atom in top left corner and a developers inspector . I tried to compile in debain 9 and Ubuntu 16 armhf same error in both . I also used a PC to cross compile that required binary and I also put the armhf one but same result .
Please give a deb file it took a long time to compile and I almost have up using atom .
please give a atom 1.23 armhf deb .
Thank you!

**Comment by hypersad** [comment]
I'm not sure that I could build a `.deb` file, but I'll try.

**Comment by dianaxxyyzz** [comment]
Please try to make a deb . You a smart guy I m sure you will succeed . I have a deb for atom 1.15 but can not use it very food because most of plugins are outdated and he recommend all time to upgrade to 1.23 .Please try to make a deb . Thanks again !

**Comment by dianaxxyyzz** [comment]
The atom build has a option to create a deb ,it may not add to the deb the plugins like 1.15 armhf deb . But the plugins can be all installed latter like in 1.15 deb instructions .

**Comment by hypersad** [comment]
Currently there is no way to build `.deb` package of Atom for `armv7l`. I can't help you now.

**Comment by hypersad** [comment]
@dianaxxyyzz `.deb` package is now available at hypersad/atom-armv7l#4.
