### ISSUE TITLE
Humble question... binaries/deb package anyone? ;)

### ISSUE THREAD

**Issue by MartinTheWanderer** [hypersad/atom-armv7l#4]
Has anyone been able to successfully compile this on RasPi 3B with current Raspian lite?

I am going bonkers here because the prerequisites outlined in https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#building result in conflicts and failed builds, for me. 

Probably just me being a noob, but frustrating. 

After hypersad made it work (THANKS!), would it be possible one of the more technically inclined users who got it running would release a .deb package for Raspian/Pi3? 

I know there are many more Raspi3 users out there who would LOVE to finally have Atom on ARM and would join me in kissing your butt for a noob-friendly package... :)

**Comment by MrEvilCookie** [comment]
As you can see in #1 , I'm failing to build it on current Raspbian on RasPi 3B, so I would like to have a .deb or at least a way to succesfully build it myself too. Installing atom and discord (which looks like is impossible so only atom) is kinda my endgame right now. :)

**Comment by hypersad** [comment]
I'll try to work on creating a `.deb` package.

**Comment by hypersad** [comment]
/cc @MartinTheWanderer @MrEvilCookie  
Although there is a `.deb` package and an archive available, I still recommend to build Atom yourself if you can, it should build successfully now.

Built on Raspberry Pi 3 Model B running Raspbian Stretch. Do not forgot to install Atom dependencies as it described [here](https://github.com/atom/atom/#archive-extraction).
[Download `.deb` package](https://yadi.sk/d/Quv-oxHB3SVSaz)
[Download archive](https://yadi.sk/d/N6NmiE3E3SVSav)

I recommend to try archive first, if you could succesfully launch Atom with `atom` binary, you could try to install `.deb` package.

**Installing `.deb` package**
1. Download `atom-armhf.deb` package above.
2. Install dependencies as it described above.
3. `sudo dpkg -i atom-armhf.deb`

Atom icon should appear in your menu.

**Extracting archive**
1. Download `atom-1.24.0-armv7l.tar.gz` archive above.
2. Install dependencies as it described above.
3. `tar -xvf atom-1.24.0-armv7l.tar.gz -C atom-1.24.0-armv7l`

You could try to launch atom with `atom` binary in `atom-1.24.0-armv7l`.

**Comment by MartinTheWanderer** [comment]
@Hypersad

WOW - thanks! 

Installing the dependencies was a mess, and all my build attempts failed, but obviously the binary works, so the build process seems to be more picky about installed node.js etc. versions than the compiled package... 

Have not tested thoroughly yet, but a quick test showed that all the usual functions seem to work. 

Thanks again, I am linking this thread on the Raspian forums, quite a few people want to use Atom on their Pi.

You are a freaking hero! ;)

![atom-arm working](https://user-images.githubusercontent.com/27972621/36341177-f5703b70-13c8-11e8-97fe-27eeb4f92f72.png)
